apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testapp
spec:
  ingressClassName: nginx
  rules:
  - host: app.201.217.240.67.nip.io
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
